name: Update README with recent activity

on:
  schedule:
    - cron: "0 */12 * * *"   # twice a day
  workflow_dispatch:           # allow manual runs

permissions:
  contents: write

jobs:
  update-activity:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Update recent activity in README
        uses: jamesgeorge007/github-activity-readme@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          COMMIT_MSG: "chore: update recent activity"
          MAX_LINES: 5
